function make_gui_v2
    % NOTE: to go fast, toggle the fields with the TAB key.
    % add components
    cd 'C:\Users\danpo\Documents\MATLAB\ephysSuite';

    %% connect to arduino
    delete(instrfindall);
    baud = 115200;
    try 
        my_s = serial('COM19','BaudRate',baud); % instrfind('Type', 'serial', 'Port', com, 'Tag', '');
        fopen(my_s); % initiate arduino communication
    catch 
        try
            my_s = serial('COM10','BaudRate',baud); % instrfind('Type', 'serial', 'Port', com, 'Tag', '');
            fopen(my_s); % initiate arduino communication
        catch
            my_s = serial('COM11','BaudRate',baud); % instrfind('Type', 'serial', 'Port', com, 'Tag', '');
            fopen(my_s); % initiate arduino communication
        end
    end
        
    
%%
    
    hs = addcomponents;
    function hs = addcomponents
        hs.fig = figure('Visible', 'on', 'Tag', 'fig');
        % same line
        hs.isiStr = uicontrol(hs.fig,...
            'Position',[50 250 70 30],...
            'Style', 'text',...
            'String','ISI');
        hs.isiEdit = uicontrol(hs.fig,...
            'Position',[100 250 70 30],...
            'Style', 'edit',...
            'String', '10',... % default, can change
            'Callback', @somethingelse,...
            'Tag', 'isi');
        % randomness
        hs.randStr= uicontrol(hs.fig,...
            'Style', 'text',...
            'Position',[150 250 70 30],...
            'String','plus or minus');
        hs.randEdit = uicontrol(hs.fig,...
            'Style', 'edit',...
            'Position',[225 250 70 30],...
            'String', '2',...
            'Tag', 'random');
        % same line
        % num trials
        hs.trialStr= uicontrol(hs.fig,...
            'Style', 'text',...
            'Position',[50 150 70 30],...
            'String','number of trials');
        hs.trialEdit = uicontrol(hs.fig,...
            'Style', 'edit',...
            'Position',[120 150 70 30],...
            'String', '20',...
            'Tag', 'trials');
        
        % Get song directory
        hs.getSongDirectory = uicontrol(hs.fig,...
            'Style', 'Edit',...
            'Position', [50 75 300 20],...
            'String', 'C:\Users\Dell\Documents\MATLAB\ephysSuite\zf son');

        % Habituate?
        hs.randomOrNah = uicontrol(hs.fig,...
            'Style', 'toggle',...
            'Position',[50 50 125 20],...
            'String','Random mode',...
            'Value',1,...
            'Callback', @changeToggleText,...
            'Tag', 'mode');
        
        % Geien sie
        hs.go = uicontrol(hs.fig,...
            'Style', 'pushbutton',...
            'Position',[50 25 125 20],...
            'String','Run',...
            'Callback', @run,...
            'Tag', 'go');
%         [from_left from_bottom width height]
        hs.progressString = uicontrol(hs.fig,...
            'Style', 'text',...
            'Position',[175 25 425 20],...
            'Tag', 'pS',...
            'String','');
        hs.elapsedTimeString = uicontrol(hs.fig,...
            'Style', 'text',...
            'Position',[175 75 425 20],...
            'Tag', 'elapsedTimeString',...
            'String','Elapsed time');
         hs.Stop = uicontrol(hs.fig,...
            'Position', [175 50 425 20],...
            'Style', 'text',...
            'String', 'Stop',...
            'Callback', @stop_exp);
    end

    function run(hObject, ~)
        isi = hs.isiEdit.String; % get(hs, 'isiEdit.String'); 
        random = hs.randEdit.String;
        trials = hs.trialEdit.String;
        isInRandMode = hs.randomOrNah.Value; % so default SHOULD BE random
        songbird_directory = hs.getSongDirectory.String;
        GuiHandle = ancestor(hObject, 'figure');
        stimulate_exp_v2(isi, random, trials, isInRandMode, songbird_directory, GuiHandle, my_s);     
    end

    function changeToggleText(hObject, ~)
        if(strcmp(get(hObject, 'String'), 'Habituate mode'))
            set(hObject, 'String', 'Random mode')
        else
            set(hObject, 'String', 'Habituate mode')
        end
    end
    
    function stop_exp(hObject, ~)
        ps = findobj(GuiHandle, 'Tag', 'pS'); % progress stirng
        ets = findobj(GuiHandle, 'Tag', 'elapsedTimeString');
        set(ps, 'String', 'Stopped');
        set(ets, 'String', ''); % make blank
        fclose(my_s); % serial        
        fclose all; % text
    end

end